#定义用户默认的连接环境
spring:
  profiles: 
    active: prod1

---  #这里是mybatis的配置环境
server:
 port: 8005  #1定义项目端口
 servlet:
   context-path: /
   #yml语法：配置时必须要有缩进，这里的缩进不能是tab，可以是空格，而且：后面必须要有空格
   #yml文件只能有一个
spring:
  datasource:
    #引入druid数据源 ，如果不配置数据源的type，则默认使用的是springboot中自带的数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    #使用最新的驱动时，连接数据库必须配置时区
    url: jdbc:mysql://127.0.0.1:3306/jtdb?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: tarena
    profiles: prod1  #定义环境的名称
  application:   #定义服务名称
      name: provider-user
eureka:    #这是注册中心的配置
  client: 
    service-url:
      defaultZone: http://localhost:7000/eureka,http://localhost:7001/eureka,http://localhost:7002/eureka
  instance:
    instance-id: provider-user-8005                #定义微服务的名称，也就是微服务在注册中心注册的名称
    prefer-ip-address: true                        #是否显示IP和端口
 
mybatis-plus:
  type-aliases-package: com.jt.springcloud.pojo
  mapper-locations: classpath:/mybatis/mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true  #自动开启驼峰规则映射
    


  
---  #添加了一个mybatis-plus的配置环境
server:
 port: 8000  #1定义项目端口
 servlet:
   context-path: /
   #yml语法：配置时必须要有缩进，这里的缩进不能是tab，可以是空格，而且：后面必须要有空格
   #yml文件只能有一个
spring:
  datasource:
    #引入druid数据源 ，如果不配置数据源的type，则默认使用的是springboot中自带的数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    #使用最新的驱动时，连接数据库必须配置时区
    url: jdbc:mysql://127.0.0.1:3306/jtdb?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: tarena
    profiles: prod2  #定义环境的名称
  application:   #定义服务名称
      name: provider-user
eureka:    #这是注册中心的配置
  client: 
    service-url:
      defaultZone: http://localhost:7000/eureka,http://localhost:7001/eureka,http://localhost:7002/eureka
  instance:
    instance-id: provider-user-8000                #定义微服务的名称，也就是微服务在注册中心注册的名称
    prefer-ip-address: true                        #是否显示IP和端口
    
#mybatis-plush配置
mybatis-plus:
  type-aliases-package: com.jt.springcloud.pojo
  mapper-locations: classpath:/mybatis/mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true  #自动开启驼峰规则映射
